### ISSUE TITLE
[3d] shader for point clouds based on color ramp

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#10]
Given a color ramp and min/max values, a shader should be able to render points with colors from the color ramp (using a 1D texture)

We already have such code for 3d mesh rendering...

**Comment by NEDJIMAbelgacem** [comment]
Check [https://github.com/qgis/QGIS/pull/40219](https://github.com/qgis/QGIS/pull/40219)
