### ISSUE TITLE
[3d] GUI for 3D renderer

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#12]
Add 3D renderer config GUI to the layer styling panel.

Initially only with point size configuration.

**Comment by nyalldawson** [comment]
Refs https://github.com/wonder-sk/point-cloud-experiments/issues/36

**Comment by NEDJIMAbelgacem** [comment]
I'm working on this here: [https://github.com/qgis/QGIS/pull/40030](url)
