### ISSUE TITLE
Write auto tests for EPT provider and core classes

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#19]
- using test dataset from #18

**Comment by nyalldawson** [comment]
Partially done -- I've added some low level tests for generic things, but nothing relating to the actual point reading for now.

**Comment by wonder-sk** [comment]
some work on that done in https://github.com/qgis/QGIS/pull/39936

**Comment by nyalldawson** [comment]
Lets close this now -- we've caught up on the backlog of missing tests, and can add new ones bit by bit as new functionality is introduced
