### ISSUE TITLE
Enable PDAL on travis

### ISSUE THREAD

**Issue by nyalldawson** [wonder-sk/point-cloud-experiments#30]

**Comment by nyalldawson** [comment]
Actually this should be deferred till after https://github.com/qgis/QGIS/pull/39815 is resolved

**Comment by wonder-sk** [comment]
Travis is on the way out, let's wait until we have a replacement (GitHub Actions probably)

**Comment by nyalldawson** [comment]
For reference, this was done in https://github.com/qgis/QGIS/pull/41467
