### ISSUE TITLE
Get required dependancies packaged for osgeo4w

### ISSUE THREAD

**Issue by nyalldawson** [wonder-sk/point-cloud-experiments#33]
And made requirements for the qgis windows package.

(Or in other words, work out what our final wishlist of packages is and then ask Jürgen nicely!)

**Comment by wonder-sk** [comment]
Jürgen is on it...

**Comment by wonder-sk** [comment]
As of today, this works for me to get QGIS with point clouds:

1. Install "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019" from here: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
2. Download the NEW osgeo4w installer: http://download.osgeo.org/osgeo4w/testing/osgeo4w-setup.exe
3. Select Advanced install and pick `qgis-dev` from the list of packages
