### ISSUE TITLE
Y coordinates seem to be rounded in 3d maps

### ISSUE THREAD

**Issue by nyalldawson** [wonder-sk/point-cloud-experiments#48]
Checkout this top down view from a 3d map, compared with the 2d render of the same region below:

![image](https://user-images.githubusercontent.com/1829991/101096349-2c421300-360b-11eb-9f97-29faf8e5d6b5.png)

The y coordinates have some rounding applied

**Comment by nyalldawson** [comment]
Here's another example:

![image](https://user-images.githubusercontent.com/1829991/101111132-4c330000-3626-11eb-8bee-45816e212262.png)

**Comment by wonder-sk** [comment]
Joy Division album cover effect :-)

**Comment by nyalldawson** [comment]
Fixed here https://github.com/qgis/QGIS/pull/40477
