### ISSUE TITLE
[2d] support for identify map tool

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#50]
Probably we should identify always just one closest point, using the list of nodes that were used also for map canvas rendering?

(Otherwise we are probably risking that we would be returning huge amounts of data in the identify results view)

**Comment by wonder-sk** [comment]
https://github.com/qgis/QGIS/pull/40569

**Comment by NEDJIMAbelgacem** [comment]
Now I'm working with the reasoning of get whatever is rendered an not getting all the points in the dataset and choosing close ones.
My current algorithm is somewhat like this:
- Have a geometry the layer coordinates
- Get all the nodes that intersect with that geometry
- Filter out the points that don't intersect with the geometry
- Filter out the points that are not rendered like the inviible classes for classification rendering
