### ISSUE TITLE
Load point clouds from Data Sources Manager

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#56]
... because some people prefer to use it to load data.

**Comment by nyalldawson** [comment]
This is already possible isn't it?

**Comment by wonder-sk** [comment]
Ahem... good point - I must have been living in a cave

![image](https://user-images.githubusercontent.com/193367/101834683-f76a1a80-3b3a-11eb-81a5-fbdb083ecfe3.png)
