### ISSUE TITLE
RGB rendering not working correctly

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#59]
At least not for this dataset:
https://pointcloud.hcmgis.vn/app/point-cloud/detail/banteay-kdei-temple-angkor-cambodia-5f6addf14bd68

The colors are quite random :-)

Additionally, if the range for R,G,B values is not set correctly, the message log ends up being flooded with huge amount of warnings like this:
```
2020-12-16T16:15:20     WARNING    QColor::setRgb: RGB parameters out of range
```

**Comment by nyalldawson** [comment]
Likely what's happening here is that untwine isn't correctly handling unsigned short attributes and somewhere internally is treating these as signed attributes, so the values from that point cloud are overflowing. (For reference entwine handles this correctly)

**Comment by wonder-sk** [comment]
Hmm but loading root node (0-0-0-0.laz) from untwine and entwine in CloudCompare gives me correctly rendered RGB point cloud in both cases... so I suspect something is wrong in our code...

**Comment by nyalldawson** [comment]
https://github.com/qgis/QGIS/pull/40735
