### ISSUE TITLE
Missing attributes in "Attribute by Ramp" renderer

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#67]
Some attributes are left out from the combo box:
- ReturnNumber
- NumberOfReturns
- ScanDirectionFlag
- EdgeOfFlightLine
- Classification
- UserData
- ScanChannel
- ClassFlags

All of these are unsigned 1-byte integers, in layer metadata they are somehow incorrectly recognized as 'Character' data type while in fact they are regular numbers in 0-255 range and it would be useful to render data based on these values.

**Comment by NEDJIMAbelgacem** [comment]
https://github.com/qgis/QGIS/pull/41050
