### ISSUE TITLE
Attribute by Ramp renderer: nothing shown if min=max

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#68]
If the minimum and maximum value is the same, then no classes are generated in the "attribute by ramp" renderer and as a result nothing gets rendered in map canvas. This is confusing for the user - it would be better to generate a single class so that at least something gets rendered.

**Comment by NEDJIMAbelgacem** [comment]
Hi @wonder-sk , I think it will be better if we don't put the attributes that has the equal min & max values in the UI in the first place.
What do you think?

**Comment by nyalldawson** [comment]
@NEDJIMAbelgacem I think that's potentially limiting -- if we have situations where the stats are missing (or incorrect) then the user would never get a choice to pick that attribute and manually set the min/max values

The fix is going to sit somewhere in QgsColorRampShader::classifyColorRamp

**Comment by wonder-sk** [comment]
Agreed with Nyall

**Comment by NEDJIMAbelgacem** [comment]
https://github.com/qgis/QGIS/pull/41078

**Comment by NEDJIMAbelgacem** [comment]
I went with the lazy way instead of messing with QgsColorRampShader :')
