### ISSUE TITLE
Attribute by Ramp renderer: auto-load min/max from stats

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#69]
When changing attribute in the GUI, the min/max values are not automatically loaded from statistics. One needs to click "Load" explicitly to get the min/max values populated which will also auto-populate classes.

It would be good to auto-load the values from statistics so that user does not need to click the Load button every time. The rationale is that most of the attributes have very different ranges of values and therefore keeping the range from previously used attribute is not that useful...

**Comment by nyalldawson** [comment]
Should be an easy fix -- I originally did this intentionally as I thought users may want to retain their classes but change attribute, but as you've pointed out there's no attributes that this actually makes sense for...

**Comment by NEDJIMAbelgacem** [comment]
https://github.com/qgis/QGIS/pull/41107
