### ISSUE TITLE
[3d] Adjustable screen error for point clouds

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#7]
Initially we have set the allowed screen error to a fixed value of 5 pixels. It would be good to make it configurable: low allowed screen error (e.g. 1px) will cause more aggressive loading of detailed data, higher will cause fewer data loads and fewer points to display.

**Comment by NEDJIMAbelgacem** [comment]
https://github.com/qgis/QGIS/pull/40451
