### ISSUE TITLE
Loading/indexing multiple LAS files

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#71]
Right now, when multiple LAS/LAZ files are loaded at once, only the first one gets indexed. This was initially done to prevent QGIS from using overwhelming amount of resources (I/O, CPU).

We should have a queue of point cloud layers waiting for indexing, and run the indexing one after the other.

Maybe in the layer tree there could be an indicator when the particular layer is a) being indexed or b) waiting to be indexed, so that users have a better idea what is going on...

**Comment by NEDJIMAbelgacem** [comment]
https://github.com/qgis/QGIS/pull/41454
