### ISSUE TITLE
[2d] RGB rendering very slow when RGB bands are missing

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#72]
And all points get rendered black. This seems to be due to the fact that when RGB attributes are missing, we set some invalid colors in QColor and Qt spits huge amount of warnings, making the rendering very slow.

**Comment by wonder-sk** [comment]
![image](https://user-images.githubusercontent.com/193367/105013764-e10b8480-5a3f-11eb-8d9f-ebe20082aa4b.png)

**Comment by saberraz** [comment]
And example dataset can be downloaded here:
https://environment.data.gov.uk/DefraDataDownload/?Mode=survey

**Comment by NEDJIMAbelgacem** [comment]
https://github.com/qgis/QGIS/pull/41106
