### ISSUE TITLE
[3d] Shape of points depends on window's aspect ratio

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#74]
When the 3D window is more or less square shaped, the points look circular (e.g. see the isolated points on the left side)

![image](https://user-images.githubusercontent.com/193367/105211278-5c5a5c80-5b4c-11eb-88eb-4fa6a9429bf5.png)

When the 3D window has rectangular shape, the points have elliptic shape

![image](https://user-images.githubusercontent.com/193367/105211521-a4797f00-5b4c-11eb-8513-963a335d1960.png)

**Comment by NEDJIMAbelgacem** [comment]
https://github.com/qgis/QGIS/pull/41122
